server:
  port: 8082
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goairdb
    username: root
    password: Admin@123
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp     